services:
  tamagotchibot:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    environment:
      - MongoUsername=${MONGO_USERNAME}
      - MongoPass=${MONGO_PASSWORD}
      - MongoIP=${MONGO_IP} # Use 'host.docker.internal' if mongo is on the host machine, or the server's IP
      - MongoPort=27017
    network_mode: "host" # Uncomment if you want the container to share the host's network stack (easier for accessing local Mongo)
